# Generated by Django 6.0.4 on 2026-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_origen', models.CharField(max_length=100)),
                ('importado_en', models.DateTimeField(auto_now_add=True)),
                ('pedidos', models.JSONField()),
                ('total_pedidos', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'importaciones externas',
                'db_table': 'importaciones_externas',
            },
        ),
    ]
