# Generated by Django 6.0.4 on 2026-05-16 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaedicionpedido',
            name='editado_por',
            field=models.ForeignKey(db_column='editado_por_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_como_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, to='pedidos.estadopedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='registrado_por',
            field=models.ForeignKey(db_column='registrado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaedicionpedido',
            name='pedido',
            field=models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, to='pedidos.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.PROTECT, to='pedidos.marca'),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='producto',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='pedidos.producto'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'creado_en'], name='idx_ped_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', 'creado_en'], name='idx_ped_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['registrado_por', 'creado_en'], name='idx_ped_registrado_por_fecha'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproducto',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='unique_pedido_producto'),
        ),
    ]
