# Generated by Django 6.0.4 on 2026-04-24 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEdicionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('pedido_antes', models.JSONField()),
                ('pedido_despues', models.JSONField()),
                ('editado_por', models.ForeignKey(db_column='editado_por_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido')),
            ],
            options={
                'verbose_name_plural': 'auditorías de edición de pedido',
                'db_table': 'auditoria_edicion_pedido',
            },
        ),
    ]
